In [8]:
def dividebyzero():
    try:
        5/0
    except ZeroDivisionError:
        print("Divide by zero in Denominator")

In [9]:
dividebyzero()

Divide by zero in Denominator


In [10]:
def formationOfSentences():
    subjects = ["Americans","Indians"]
    verbs = ["play","watch"]
    objects = ["Baseball","Cricket"]
    
    for subject in subjects:
        for verb in verbs:
            for obj in objects:
                print(subject + " "+ verb +" " + obj)
    
    

In [11]:
formationOfSentences()

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [55]:
import math
import numpy as np
def vander_matrix(num_array = [], increasing = True):
    mat = [[0 for x in range(len(num_array))] for y in range(len(num_array))]
    
    for i in range(len(num_array)):
        for j in range(len(num_array)):
            if increasing:
                mat[i][j] = math.pow(num_array[i],j)
            else:
                mat[i][j] = math.pow(num_array[i], len(num_array) - j -1 )
        
    print(np.array(mat))

In [56]:
vander_matrix([1,2,3,4,5], increasing = False)

[[  1.   1.   1.   1.   1.]
 [ 16.   8.   4.   2.   1.]
 [ 81.  27.   9.   3.   1.]
 [256.  64.  16.   4.   1.]
 [625. 125.  25.   5.   1.]]
